on:
  push:
    branches: [main]
  release:
    types: [prereleased, released]
  workflow_dispatch:
    inputs:
      apps:
        description: Comma-separated list of applications to build
        required: true
        type: string
      env:
        default: dev
        description: Environment to deploy application
        required: true
        type: string
      ref:
        default: main
        description: Branch, tag, or SHA to deploy application from
        required: true
        type: string
name: Deploy
env:
  ENVIRONMENT: >-
    ${{ ( ( github.event_name == 'release' && github.event.release.prerelease != true ) || ( contains( github.event.inputs.env, 'prod' ) == 'true' ) && 'prod' ) ||
        ( ( github.event_name == 'release' && github.event.release.prerelease == true ) || ( contains( github.event.inputs.env, 'qa' ) == 'true' ) && 'qa' ) ||
        ( (github.event_name == 'push') || ( contains( github.event.inputs.env, 'dev' ) == 'true' ) && 'dev') }}
  URL: >-
    ${{ ( ( github.event_name == 'release' && github.event.release.prerelease != true ) || ( contains( github.event.inputs.env, 'prod' ) == 'true' ) && 'https://my.premise.com' ) ||
        ( ( github.event_name == 'release' && github.event.release.prerelease == true ) || ( contains( github.event.inputs.env, 'qa' ) == 'true' ) && 'https://qa.my.premise.com' ) ||
        ( (github.event_name == 'push') || ( contains( github.event.inputs.env, 'dev' ) == 'true' ) && 'https://dev.my.premise.com') }}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Echoing
        run: echo "${{ env.ENVIRONMENT }} - ${{ env.URL }}"
